### ISSUE TITLE
binary request

### ISSUE THREAD

**Issue by ghost** [Neo-Desktop/3d-pinball-space-cadet#1]
Love it! could you provide an 32 bit arm (armhf) build to run it with wine ARM??
I mean I have all the libs to build this project, but we dont have dx on linux. Running on wine could use it on software mode.

**Comment by Neo-Desktop** [comment]
thanks for the input!
at this point, the sources don't even compile
once the project is in a better place, binaries will be provided :)

**Comment by ghost** [comment]
such memories.. also, like this one https://www.youtube.com/watch?v=kxMOM24odF0
amazing stuff

**Comment by parkerlreed** [comment]
@Neo-Desktop Ahh thanks. Good to know!

**Comment by ghost** [comment]
Check this out @Neo-Desktop 
Box86 it's reaching wine x86 , this was ny first test. It will just require some workaround with pulse.. more testing to come!
Anyway, your dissasembled version would be quite useful for enhancements porpoises

https://www.youtube.com/watch?v=gkwglDJ2kzQ&feature=youtu.be

**Comment by parkerlreed** [comment]
It's not compiling in any state. When it does start to get worked on, it won't need box86 to translate. It will just compile natively for the platform.

Good to see it running though

**Comment by ghost** [comment]
Obviusly I understand the difference from native and emulated. But just to let you know they are other approaches too. This would be much better down the road, especially for all the enhancements than can be done with the source code.

**Comment by Neo-Desktop** [comment]
Thank you for your support - please visit [@k4zmu2a/SpaceCadetPinball](https://github.com/k4zmu2a/SpaceCadetPinball) for a working version
