### ISSUE TITLE
Project doesnt compile on Win10, VS19

### ISSUE THREAD

**Issue by GHXX** [Neo-Desktop/3d-pinball-space-cadet#2]
Hey, i cloned your repository and tried to get it to compile on Windows 10 using Visual Studio 2019, but it seems that its missing a SDL.h header file aswell as a file called Defs.h

Would it be possible for you to include these files / describe how to set up the project in the readme?

My goal is to compile a version with better resolution and possibly a higher framerate than the original to make it more enjoyable

**Comment by Neo-Desktop** [comment]
I have to be clear that this disassembly is still a work in progress.
It's by no means compile-able right now, and unfortunately, I haven't worked on this for some time - I am looking forward to doing so soon.

You are welcome to make changes to the code and open a pull request when necessary

Thanks

**Comment by Neo-Desktop** [comment]
Thank you for your support - please visit [@k4zmu2a/SpaceCadetPinball](https://github.com/k4zmu2a/SpaceCadetPinball) for a working version
