### ISSUE TITLE
CMakeLists.txt looking for SDL2 at hardcoded Windows paths?

### ISSUE THREAD

**Issue by parkerlreed** [Neo-Desktop/3d-pinball-space-cadet#3]
This makes trying to build on Linux not work as it can't find SDL.h. I tried modifying the file to use the SDL include directive but still can't get it working.

**Comment by Neo-Desktop** [comment]
I have to be clear that this disassembly is still a work in progress.
It's by no means compile-able right now, and unfortunately, I haven't worked on this for some time - I am looking forward to doing so soon.

I've included SDL in the codebase as a means to migrate from the windows GDI functions to something cross-platform-compatible. SDL seemed to be the fastest way forward in that situation.
I don't think I've written any SDL code at this time. It was merely an inclusion of the framework

You are welcome to make changes to the code and open a pull request when necessary

Thanks

**Comment by coreybruce** [comment]
Cant wait to see this completed, keep up the great work! :D

**Comment by Neo-Desktop** [comment]
Thank you for your support - please visit [@k4zmu2a/SpaceCadetPinball](https://github.com/k4zmu2a/SpaceCadetPinball) for a working version
